# Generated by Django 5.2.9 on 2025-12-05 07:39

import api.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.CharField(default=api.models.generate_beneficiary_id, editable=False, max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('location', models.CharField(blank=True, max_length=256)),
                ('consent_given', models.BooleanField(default=False)),
                ('location_type', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('pincode', models.CharField(blank=True, max_length=20, null=True)),
                ('household_size', models.PositiveIntegerField(blank=True, null=True)),
                ('education_level', models.CharField(blank=True, max_length=100, null=True)),
                ('marital_status', models.CharField(blank=True, max_length=50, null=True)),
                ('ration_card_type', models.CharField(blank=True, max_length=50, null=True)),
                ('govt_subsidy_received', models.BooleanField(default=False)),
                ('aadhaar_verified', models.BooleanField(default=False)),
                ('pan_available', models.BooleanField(default=False)),
                ('bank_account_active', models.BooleanField(default=False)),
                ('income_est', models.FloatField(blank=True, null=True)),
                ('estimated_monthly_income', models.FloatField(blank=True, null=True)),
                ('income_category', models.CharField(blank=True, max_length=50, null=True)),
                ('employment_type', models.CharField(blank=True, max_length=50, null=True)),
                ('work_consistency_days', models.PositiveIntegerField(blank=True, null=True)),
                ('eligibility_label', models.CharField(blank=True, max_length=50, null=True)),
                ('model_score', models.FloatField(blank=True, null=True)),
                ('approval_flag', models.BooleanField(blank=True, null=True)),
                ('other_details', models.JSONField(blank=True, default=dict, null=True)),
                ('risk_band', models.CharField(blank=True, max_length=50, null=True)),
                ('need_band', models.CharField(blank=True, max_length=50, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('eligibility', models.CharField(blank=True, max_length=50, null=True)),
                ('number_of_loans', models.PositiveIntegerField(blank=True, help_text='Total number of loans', null=True)),
                ('emi_due_delays', models.PositiveIntegerField(blank=True, help_text='No. of delayed EMIs', null=True)),
                ('credit_card_available', models.BooleanField(blank=True, help_text='Has credit card?', null=True)),
                ('cibil_score', models.PositiveIntegerField(blank=True, help_text='Reported CIBIL score', null=True)),
                ('case_type', models.CharField(blank=True, choices=[('CASE1', 'Case 1'), ('CASE2', 'Case 2'), ('CASE3', 'Case 3'), ('CASE4', 'Case 4')], help_text='One of CASE1 / CASE2 / CASE3 / CASE4', max_length=10, null=True)),
                ('loans_dues_change_reason', models.TextField(blank=True, help_text='Reason for changing number of loans or EMI due delays after first submission', null=True)),
                ('otp_code', models.CharField(blank=True, max_length=6, null=True)),
                ('otp_created_at', models.DateTimeField(blank=True, null=True)),
                ('is_phone_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_beneficiaries', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beneficiaries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AIScoreLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.FloatField()),
                ('risk_band', models.CharField(max_length=50)),
                ('need_band', models.CharField(max_length=50)),
                ('explanation', models.TextField()),
                ('model_used', models.CharField(default='fallback', max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_logs', to='api.beneficiary')),
            ],
        ),
        migrations.CreateModel(
            name='CaseDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_type', models.CharField(blank=True, choices=[('CASE1', 'Case 1'), ('CASE2', 'Case 2'), ('CASE3', 'Case 3'), ('CASE4', 'Case 4')], max_length=10, null=True)),
                ('electricity_units', models.PositiveIntegerField(blank=True, null=True)),
                ('electricity_bill', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payments_regularity', models.BooleanField(blank=True, help_text='Are payments regular? (Yes/No)', null=True)),
                ('average_mobile_bill', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gas_bill', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gas_frequency', models.CharField(blank=True, max_length=50, null=True)),
                ('employment_type', models.CharField(blank=True, max_length=150, null=True)),
                ('working_days_per_month', models.PositiveIntegerField(blank=True, null=True)),
                ('digital_payment_frequency', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10, null=True)),
                ('average_bank_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cash_inflow', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cash_outflow', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('transactions_per_month', models.PositiveIntegerField(blank=True, null=True)),
                ('last_6_months_avg_bank_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_properties_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('wealth_index', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('any_business', models.BooleanField(blank=True, null=True)),
                ('insurance_coverage', models.BooleanField(blank=True, null=True)),
                ('luxury_expenditures', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('outstanding_bank_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('loan_purpose', models.CharField(blank=True, max_length=256, null=True)),
                ('loan_history_cibil', models.TextField(blank=True, null=True)),
                ('reasons_for_delay', models.TextField(blank=True, null=True)),
                ('number_of_active_loans', models.PositiveIntegerField(blank=True, null=True)),
                ('total_emi_per_month', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('number_of_due_delays', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('beneficiary', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='case_details', to='api.beneficiary')),
            ],
        ),
        migrations.CreateModel(
            name='ConsumptionData',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('electricity_bill', models.FloatField(blank=True, null=True)),
                ('mobile_bill', models.FloatField(blank=True, null=True)),
                ('other_bills', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumption_records', to='api.beneficiary')),
            ],
        ),
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tenure_months', models.IntegerField()),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('decision_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_applications', to='api.beneficiary')),
                ('officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_loans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LoanHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('tenure', models.PositiveIntegerField()),
                ('repayment_status', models.CharField(default='Pending', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='api.beneficiary')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('beneficiary', 'Beneficiary'), ('officer', 'Officer')], default='beneficiary', max_length=20)),
                ('picture', models.URLField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BeneficiaryDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('AADHAAR', 'Aadhaar Card'), ('PAN', 'PAN Card'), ('ELECTRICITY', 'Electricity Bill'), ('MOBILE', 'Mobile Bill'), ('WATER', 'Water Bill'), ('GAS', 'Gas Bill')], max_length=20)),
                ('document_number', models.CharField(help_text='Aadhaar number / PAN number / consumer number / phone number etc.', max_length=100)),
                ('image', models.ImageField(blank=True, help_text='Scanned copy or photo of the document', null=True, upload_to='beneficiary_docs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='api.beneficiary')),
            ],
            options={
                'unique_together': {('beneficiary', 'doc_type')},
            },
        ),
    ]
